### ISSUE TITLE
Wwise exporter

### ISSUE THREAD

**Issue by Jespercal** [dalokraff/mastergriller#1]
Hello dalokraff,

I have been trying to figure out how to add sounds to VT2 and see you've managed to do it, so I was hoping you could help me with the final details.

I have been able to make a bank from wwise, but it's in the format .bnk and doesn't work with the game's version. How did you manage to get the correct version?

**Comment by dalokraff** [comment]
> I have been able to make a bank from wwise, but it's in the format .bnk and doesn't work with the game's version. How did you manage to get the correct version?

Currently most of the information on this is in the [Vermintide Modder's Discord](https://discord.gg/XwST7fN), you can also find the link at the bottom of the vermintide 2 sdk's readme . [Here's](https://discord.com/channels/404978161726783489/440564700451831829/1023606910777307277) a post I made that more or less outlines the topic and provides relevant message links.

In case you don't want to use discord, I'll give a rundown here but you will have to download a tool a that's currently only avaible through a discord download link.
You'll need to use a [post production tool provided by FatShark MannyBlanc](https://cdn.discordapp.com/attachments/440564700451831829/930196953801850991/wwise_exporter.exe) and [another one by community member Sir Aeidal](https://gitlab.com/lschwiderski/vt2_wwise_fix/-/packages). The first is for generating the proper bank files and the second for modifying the header version (the second you can do yourself pretty easily, it's just change a few bytes). 

In the "User Settings" menu of the SoundBank Manager you'll need to click the "Override Project Post-Generation Step". And then put in these commands with the appropriate paths, their respective executables:

For FS's exporter
`"$(WwiseExePath)\CopyStreamedFiles.exe" -info "$(InfoFilePath)" -outputpath "$(SoundBankPath)" -banks "$(SoundBankList)" -languages "$(LanguageList)"
"D:\PATH\TO\wwise_exporter.exe" $(Platform) "$(SoundBankPath)" "D:\PATH\TO\CONTENT" "wwise" $(SoundBankListAsTextFile)`

For Sir Aeidal's executable
`"D:\wwise_fix.exe" "D:PATH/TO/MODS/WWISE/FOLDER"`

**Comment by Jespercal** [comment]
Thank you so much!
To be honest, it didn't occur to me to check out the Discord, even though I knew it existed, but I see now how much help and information is in there.
Once again, thank you for the help 🙂
